### ISSUE TITLE
Interest in supporting video datasets?

### ISSUE THREAD

**Issue by TheShadow29** [rom1504/img2dataset#190]
Hi. Thanks for the amazing repository. It really makes the workflow very easy. I was wondering if you are considering to add video datasets as well. Some are based on urls, while some others are derived from youtube or segments from youtube.

**Comment by rom1504** [comment]
Hi, indeed video is interesting!

I'm collaborating with Maciej on https://github.com/iejMac/video2numpy and https://github.com/iejMac/clip-video-encode recently
The first one gets frames from videos, the second gets clip embeddings from frames

Not fully ready for use yet, but I think that kind of packaging makes sense.

Encoding videos is less obvious than images: directly downloading and storing doesn't make a lot of sense due to their large size, so various encoding options should be explored (small resolution, clip, vqgan,...) and used inside a tool like img2dataset

**Comment by TheShadow29** [comment]
@rom1504 Ah, interesting. I wasn't aware of video2numpy project. If I understand correctly, it would store it individual frames but that would result in very large files. Webdataset has some recommendations on directly saving the .mp4 files into tar format (https://webdataset.github.io/webdataset/video-loading-example/), maybe that case is simpler. 

Another way would be to use ffmpeg or decord to subsample and resize the videos.

**Comment by rom1504** [comment]
> If I understand correctly, it would store it individual frames but that would result in very large files. 

no not exactly. The idea of this module is to subsamples frames at eg 1fps and provide them to user through shared memory / a generator so that user modules can actually represent the dataset in an useful way

storing raw frames would be very big indeed, hence the clip-video-encode dataset that allow storing clip embedding instead
other paths include resizing and storing only small frames, and yet another pass is to store image sequences using vqgan

**Comment by rom1504** [comment]
it would probably be possible to directly use video2numpy in a data loader for people that want to train on raw frames (but that seems difficult)

**Comment by TheShadow29** [comment]
Currently, codebases like pytorchvideo are using pyav, ffmpeg or decord to extract raw frames from mp4 files. Training on kinetics requires high fps (30) for models such as SlowFast.

**Comment by rom1504** [comment]
yeah we've been targeting much lower fps but that's interesting

**Comment by rom1504** [comment]
see https://github.com/iejMac/video2dataset
