### ISSUE TITLE
update fsspec

### ISSUE THREAD

**Issue by rom1504** [rom1504/img2dataset#239]

**Comment by RobbeSneyders** [comment]
Is there a reason to limit `fsspec` to a single version? This is currently keeping us from using `img2dataset` as a dependency due to dependency conflicts, and requires us to copy in part of the code instead.

**Comment by rom1504** [comment]
The version structure of fsspec (it uses year.month.day and not major.minor.patch) that is not following semver prevents depending on one major and letting the minor change.

That leaves these choices:
1. Depending on one version and being sure this one works (thanks to CI checking it)
2. Removing the version requirement completely, so users would get no guarantee on fsspec working well with fsspec
3. Keeping a minimum fsspec version, hoping new "major versions" will not be breaking
4. Making a random guess on what the last supported "major" should be (maybe 3 months from now)
5. Asking fsspec to use semver

We're currently doing 1.

I think 5 is the best solution but if they would agree it would take some time and it's not sure they'd agree to such a bit change.

Maybe 4 is an ok compromise?
Eg we switch to the current last fsspec and allow up to 2024.01.00
Would that work for you ?

**Comment by RobbeSneyders** [comment]
Since there's no semantic meaning to the versions, I would argue that 3 is the best option. You indicate a minimum compatible version while keeping options open for the user. The user should pin their versions instead.

Ideally you catch deprecation warnings in your tests to catch breaking changes before they happen, but otherwise you can update the dependency in the release after a breaking change.

**Comment by rom1504** [comment]
The problem with 3 is that maybe the latest version of fsspec does not work with img2dataset and was not tested to work in the CI. This is the version that will be installed by users so users will start reporting things don't work

**Comment by RobbeSneyders** [comment]
Yes, but users can fix it on their side. With the current solution, there's no way for us to fix it, since there's a conflict with the pinned version.

Also, when releasing img2dataset, the latest version of `fsspec` should work. So if users pin their versions from the start, they will not run into issues.

Here's a couple of long reads which discuss the topic:
https://iscinumpy.dev/post/bound-version-constraints/ 
https://hynek.me/articles/semver-will-not-save-you/ (a bit shorter)

While I don't agree with abandoning SemVer, I do agree with the solution if a dependency abandons it :slightly_smiling_face:

**Comment by rom1504** [comment]
I decided to just remove the version restriction on fsspec. That's done and released now
