### ISSUE TITLE
Support recording image license

### ISSUE THREAD

**Issue by tomchiverton** [rom1504/img2dataset#294]
No attempt is made to record (or respect) the license of the ingested content.

This is likely to cause issues for any subsequent use.

**Comment by rom1504** [comment]
Yes, it is the responsibility of the user to use images in a way that respects the law

If you have some ideas of how to collect the license of content and save it in the output metadata, it could be interesting. I am not aware of any working method to do that.

**Comment by tomchiverton** [comment]
You could for instance check for rel="licence" or common licence strings such as CC-BY
-- 
†øღ

**Comment by rom1504** [comment]
That's not possible from image urls

**Comment by rom1504** [comment]
You are free to not use the tool

**Comment by rec** [comment]
Your tool is set up so that even a conscientious user who wished to obey licensing restrictions would find it impossible, and the average user would simply have no idea that any licensing terms exist.

People very reasonably want to protect their intellectual property and their bandwidth from users of your program.

Ethically, if you create a tool which works in a way to encourage unethical behavior and many people use it this way, you bear responsibility for the consequences of your actions.

"You are free to not use the tool" is not a respectful response: it does not give them any way to solve or mitigate the problem, or even acknowledge it is a real issue. It is hard not to see it as just mockery.

**Comment by rom1504** [comment]
This tool is encouraging ethical behavior. Many people are using it this way, see for example all the papers that are citing laion5B paper and advancing science.

Collection of license is not something a tool that downloads urls can do. It can possibly be done in other tools.
As to whether it would help to collect these licenses, that's yet another question and the answer is far from obvious.
Regardless, this is far outside the scope of this tool.

It seems you want to talk to users of text to image models and forbid them to generate images.
