### ISSUE TITLE
follow up of wandb PR

### ISSUE THREAD

**Issue by rom1504** [rom1504/img2dataset#44]
There are some issues left:
* use of global script wise variables: globals are bad and here really not needed, it's all happening in download function
* display sample/s metric, the rest is too implementation specific
* check if implementation can be simplified: using half the script for logging seems to be too much

**Comment by rom1504** [comment]
I think I'm going to revert this PR, and we can try again
the code is too complex, it's going to make it hard to move forward, and it doesn't aggregated in meaningful ways

(also getting reports it doesn't work on colab)

simplicity is crutial for performance critical code

**Comment by rom1504** [comment]
Here are the main interesting features we want here:
* logging sample/s
* logging success rate
* maybe logging error statuses
* logging image width/height ?

What we want to avoid:
* making the code complex
* introducing hard dependencies / global variables between main process and subprocess (to make it easier to move to alternative process managers in the future)

https://github.com/rom1504/img2dataset/pull/40/files was a nice starting point, but needs more work

I think we should:
* remove completely the global (cumulated) metrics
* emit metrics from workers with iterators or with return
* aggregated workers metrics in main and send to wandb

it should be possible to do this and keeping it simple

**Comment by borisdayma** [comment]
Ok, a few comments:

* the logging functionality takes some space because it handles "per process" and "global" through one class, as well as minimum time for logging (due to the tables). Not sure how cleaner it can be but I would have just moved it to another file
* For colab bug, we could have a flag `use_wandb` and leave it off by default until the colab bug is fixed (don't think there's many issues as I've been using it a lot already in local and cloud services)
* logging image width/height is already done in your parquet so didn't think it would be useful and the table would be huge. If you're talking about the input parameters they're already logged as config
* for the global variable I think I had something different initially and forgot that they didn't need to be global anymore after I refactored (because I wanted to avoid global variables). We would just have to remove the `global` keyword and init them there.
* After I added the table status, I agree we could have just removed the other error metrics and keep only `img_per_sec` and `success_rate`
* I actually personally like having metrics per process and cumulated ones (equivalent to average) for debugging.
  * For example I was downloading the WIT (wikipedia) dataset and [this run](https://wandb.ai/borisd13/img2dataset/runs/gufxdg6u?workspace=user-borisd13) shows me that when having too many processes at the same time (even only 4), I have 93% success rate on 1 process (rest are urls not valid) and 0% on the others which return "HTTP Error 429: Too Many Requests". In the end it helped me find the best process/thread counts needed for that dataset.
  * Also my connection is not always reliable (either due to DNS errors or lower speeds) so I like comparing the "per process" performance vs the cumulated/average one
* W&B workflow typically wants you to log all the raw data and you can define custom plots (average, custom formula, etc) for more specific use cases but I don't think it's needed here
* I actually had an idea for adding the metrics we think are the most important at the top (using `define_metric`). Then it's always useful to display all other metrics for debugging and power users.

**Comment by rom1504** [comment]
> logging image width/height is already done in your parquet so didn't think it would be useful and the table would be huge. If you're talking about the input parameters they're already logged as config

I meant statistics, like average width/height, maybe some quantiles

for the rest I mostly agree, I'm working now on putting back your changes

**Comment by rom1504** [comment]
now mostly done

for anything left, it can be tracked in other issues if needed

**Comment by borisdayma** [comment]
For your image statistics, you may be interested in the [histogram feature](https://docs.wandb.ai/guides/track/log/media#histograms)
